### ISSUE TITLE
Integrar Nueva Fuente de Precio MXNUSD -- Oráculo de UMA

### ISSUE THREAD

**Issue by iafhurtado** [PipilaDAO/frontend#30]
UMA tiene una fuente del precio MXNUSD de parte de TraderMade.

UMA Docs -- Price IDs: https://docs.umaproject.org/uma-tokenholders/approved-price-identifiers
TraderMade Currencies Supported: https://marketdata.tradermade.com/live-currencies-list
UMA UMIPs Github -- https://github.com/UMAprotocol/UMIPs/blob/master/UMIPs/umip-139.md

**Comment by 0xnook** [comment]
Esto no tiene que ver con frontend, perosi con los contratos PipilaDAO/xocolat#25
